
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Loja1._0.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Contabilidade
{

    public int id { get; set; }

    public Nullable<decimal> caixa { get; set; }

    public Nullable<decimal> banco { get; set; }

    public Nullable<decimal> a_receber_cp { get; set; }

    public Nullable<decimal> a_pagar_cp { get; set; }

    public Nullable<decimal> a_receber_lp { get; set; }

    public Nullable<decimal> a_pagar_lp { get; set; }

    public Nullable<decimal> imposto_recolher { get; set; }

    public Nullable<decimal> moveis_utensilios { get; set; }

    public Nullable<decimal> maquinario { get; set; }

    public Nullable<decimal> imovel { get; set; }

    public Nullable<decimal> veiculos { get; set; }

    public Nullable<decimal> salarios { get; set; }

    public Nullable<decimal> fornecedores { get; set; }

    public Nullable<decimal> clientes { get; set; }

    public Nullable<decimal> despesas { get; set; }

    public Nullable<decimal> estoques { get; set; }

    public Nullable<decimal> cap_soc_integ { get; set; }

    public Nullable<decimal> cap_soc_n_integ { get; set; }

    public Nullable<decimal> lucro { get; set; }

    public Nullable<decimal> pro_labore { get; set; }

}

}
