//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtrlPonto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CtrlPonto()
        {
            this.LogPonto = new HashSet<LogPonto>();
        }
    
        public int Id { get; set; }
        public int Id_User { get; set; }
        public System.DateTime Dt_Ponto { get; set; }
        public Nullable<System.TimeSpan> Entrada { get; set; }
        public Nullable<System.TimeSpan> Saida_Almoco { get; set; }
        public Nullable<System.TimeSpan> Retorno_Almoco { get; set; }
        public Nullable<System.TimeSpan> Saida { get; set; }
        public bool Falta { get; set; }
        public Nullable<System.TimeSpan> Compensacao { get; set; }
        public string Observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPonto> LogPonto { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
