//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gerenciamento
    {
        public int Id { get; set; }
        public double comissao { get; set; }
        public double percIcms { get; set; }
        public double autoDescPerc { get; set; }
        public decimal autoDescValor { get; set; }
        public double maxDescPerc { get; set; }
        public double jurosPrazo3x { get; set; }
        public double jurosPrazo4x { get; set; }
        public double jurosPrazo5x { get; set; }
        public double jurosPrazo6x { get; set; }
        public double jurosPrazo7x { get; set; }
        public double jurosPrazo8x { get; set; }
        public double jurosPrazo9x { get; set; }
        public double jurosPrazo10x { get; set; }
        public double jurosPrazo11x { get; set; }
        public double jurosPrazo12x { get; set; }
        public double jurosCheque2x { get; set; }
        public double jurosCheque3x { get; set; }
        public double jurosCheque4x { get; set; }
        public double jurosCheque5x { get; set; }
        public double jurosCheque6x { get; set; }
        public double jurosCheque7x { get; set; }
        public double jurosCheque8x { get; set; }
        public double jurosCheque9x { get; set; }
        public double jurosCheque10x { get; set; }
        public double jurosCheque11x { get; set; }
        public double jurosCheque12x { get; set; }
        public double lucroMinimo { get; set; }
    }
}
