//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gerenciamento
    {
        public int id { get; set; }
        public decimal comissao { get; set; }
        public decimal tributacao { get; set; }
        public decimal autoDescPerc { get; set; }
        public decimal autoDescValor { get; set; }
        public int maxDescPerc { get; set; }
        public decimal jurosPrazo2x { get; set; }
        public decimal jurosPrazo3x { get; set; }
        public decimal jurosPrazo4x { get; set; }
        public decimal jurosPrazo5x { get; set; }
        public decimal jurosPrazo6x { get; set; }
        public decimal jurosPrazo7x { get; set; }
        public decimal jurosPrazo8x { get; set; }
        public decimal jurosPrazo9x { get; set; }
        public decimal jurosPrazo10x { get; set; }
        public decimal jurosPrazo11x { get; set; }
        public decimal jurosPrazo12x { get; set; }
        public decimal jurosCheque1x { get; set; }
        public decimal jurosCheque2x { get; set; }
        public decimal jurosCheque3x { get; set; }
        public decimal jurosCheque4x { get; set; }
        public decimal jurosCheque5x { get; set; }
        public decimal jurosCheque6x { get; set; }
        public decimal jurosCheque7x { get; set; }
        public decimal jurosCheque8x { get; set; }
        public decimal jurosCheque9x { get; set; }
        public decimal jurosCheque10x { get; set; }
        public decimal jurosCheque11x { get; set; }
        public decimal jurosCheque12x { get; set; }
        public decimal lucroMinimo { get; set; }
    }
}
