//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPonto
    {
        public int id { get; set; }
        public int id_Ponto { get; set; }
        public string valor { get; set; }
        public int id_User { get; set; }
        public System.DateTime dt_Alteracao { get; set; }
    }
}
