
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Loja1._0.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Movimentos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Movimentos()
    {

        this.Pagamentos = new HashSet<Pagamentos>();

    }


    public int id { get; set; }

    public string desc { get; set; }

    public Nullable<decimal> valor { get; set; }

    public Nullable<System.DateTime> data { get; set; }

    public Nullable<int> id_tipo { get; set; }



    public virtual Tipos_Movimentacao Tipos_Movimentacao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pagamentos> Pagamentos { get; set; }

}

}
