//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.Vendas_Produtos = new HashSet<Vendas_Produtos>();
        }
    
        public int id { get; set; }
        public string cod_produto { get; set; }
        public string desc_produto { get; set; }
        public int id_medida { get; set; }
        public decimal preco_compra { get; set; }
        public decimal preco_venda { get; set; }
        public decimal ICMS_pago { get; set; }
        public byte[] imagem { get; set; }
        public int id_fornecedor { get; set; }
        public int status { get; set; }
    
        public virtual Estoque Estoque { get; set; }
        public virtual UnidMedidas UnidMedidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendas_Produtos> Vendas_Produtos { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
    }
}
