
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Loja1._0.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Tipos_Movimentacao
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tipos_Movimentacao()
    {

        this.Movimentos = new HashSet<Movimentos>();

    }


    public int id { get; set; }

    public string descricao { get; set; }

    public string direcao { get; set; }

    public string sub_tipo { get; set; }

    public string conta { get; set; }

    public string forma_pag { get; set; }

    public Nullable<bool> mostrar { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Movimentos> Movimentos { get; set; }

}

}
