
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Loja1._0.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Usuarios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuarios()
    {

        this.Vendas = new HashSet<Vendas>();

    }


    public int id { get; set; }

    public Nullable<int> registro { get; set; }

    public string nome { get; set; }

    public string senha { get; set; }

    public int num_perfil { get; set; }

    public int status { get; set; }



    public virtual Perfis Perfis { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vendas> Vendas { get; set; }

}

}
