
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Loja1._0.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Usuarios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuarios()
    {

        this.CtrlPonto = new HashSet<CtrlPonto>();

        this.Vendas = new HashSet<Vendas>();

    }


    public int id { get; set; }

    public string login { get; set; }

    public string nome { get; set; }

    public string cpf { get; set; }

    public string rg { get; set; }

    public string registro { get; set; }

    public string senha { get; set; }

    public Nullable<int> id_Perfil { get; set; }

    public System.TimeSpan bancoHoras { get; set; }

    public Nullable<decimal> salario { get; set; }

    public int status { get; set; }

    public Nullable<System.DateTime> dt_Inclusao { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CtrlPonto> CtrlPonto { get; set; }

    public virtual Perfis Perfis { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vendas> Vendas { get; set; }

}

}
